# Generated by Django 5.0.6 on 2024-06-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='age',
            new_name='desc',
        ),
    ]
