# Generated by Django 5.0.6 on 2024-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_students_book_rename_age_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='default.jpg', upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
